version: "3.8"

services:

  config:
    image: nexgen/config:latest
    mem_limit: 700m
    ports:
      - "8888:8888"
    networks:
      - nexgen-network
    
  eureka:
    image: nexgen/eureka:latest
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - nexgen-network
    depends_on:
      - config
    environment:
        SPRING_PROFILES_ACTIVE: default
        SPRING_CONFIG_IMPORT: configserver:http://config:8888/
    
  gateway:
    image: nexgen/gateway:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - nexgen-network
    depends_on:
      - config
      - eureka
    environment:
        SPRING_PROFILES_ACTIVE: default
        SPRING_CONFIG_IMPORT: configserver:http://config:8888/
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/ 
        
  ping:
    image: nexgen/ping:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - nexgen-network
    depends_on:
      - config
      - eureka
      - gateway
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
        SPRING_PROFILES_ACTIVE: default
        SPRING_CONFIG_IMPORT: configserver:http://config:8888/
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/ 
         
networks:
  nexgen-network: